import { WordAndTranscription } from "../../../interfaces/word";

export const wordsImitation: WordAndTranscription[] = [
    { word: "Peteca", transcription: ["p", "e", "t", "ɛ", "k", "ɐ"] },
    { word: "Bandeja", transcription: ["b", "ɐ̃", "d", "e", "ʒ", "ɐ"] },
    { word: "Tigela", transcription: ["t", "i", "ʒ", "ɛ", "l", "ɐ"] },
    { word: "Doce", transcription: ["d", "o", "s", "i"] },
    { word: "Cortina", transcription: ["k", "o", "ʁ", "t", "i", "n", "ɐ"] },
    { word: "Gato", transcription: ["g", "a", "t", "u"] },
    { word: "Foguete", transcription: ["f", "o", "g", "e", "t", "i"] },
    { word: "Vinho", transcription: ["v", "ĩ", "ɲ", "u"] },
    { word: "Selo", transcription: ["s", "e", "l", "u"] },
    { word: "Zero", transcription: ["z", "ɛ", "ɾ", "u"] },
    { word: "Chuva", transcription: ["ʃ", "u", "v", "ɐ"] },
    { word: "Jacaré", transcription: ["ʒ", "a", "k", "a", "ɾ", "ɛ"] },
    { word: "Machado", transcription: ["m", "a", "ʃ", "a", "d", "u"] },
    { word: "Nata", transcription: ["n", "a", "t", "ɐ"] },
    { word: "Lama", transcription: ["l", "ɐ", "m", "ɐ"] },
    { word: "Ônibus", transcription: ["õ", "n", "i", "b", "u", "s"] },
    { word: "Prego", transcription: ["p", "ɾ", "e", "g", "u"] },
    { word: "Café", transcription: ["k", "a", "f", "ɛ"] },
    { word: "Alface", transcription: ["a", "w", "f", "a", "s", "i"] },
    { word: "Raposa", transcription: ["ʁ", "a", "p", "o", "z", "ɐ"] },
    { word: "Borracha", transcription: ["b", "o", "ʁ", "a", "ʃ", "ɐ"] },
    { word: "Abelha", transcription: ["a", "b", "e", "ʎ", "ɐ"] },
    { word: "Carro", transcription: ["k", "a", "ʁ", "u"] },
    { word: "Branco", transcription: ["b", "ɾ", "ɐ̃", "k", "u"] },
    { word: "Travessa", transcription: ["t", "ɾ", "a", "v", "ɛ", "s", "ɐ"] },
    { word: "Dragao", transcription: ["d", "ɾ", "a", "g", "ɐ̃", "w"] },
    { word: "Cravo", transcription: ["k", "ɾ", "a", "v", "u"] },
    { word: "Grosso", transcription: ["g", "ɾ", "o", "s", "u"] },
    { word: "Fraco", transcription: ["f", "ɾ", "a", "k", "u"] },
    {
        word: "Plástico",
        transcription: ["p", "l", "a", "s", "t", "i", "k", "u"],
    },
    { word: "Bloco", transcription: ["b", "l", "ɔ", "k", "u"] },
    { word: "Clube", transcription: ["k", "l", "u", "b", "i"] },
    { word: "Globo", transcription: ["g", "l", "o", "b", "u"] },
    { word: "Flauta", transcription: ["f", "l", "a", "w", "t", "ɐ"] },
    { word: "Pastel", transcription: ["p", "a", "s", "t", "ɛ", "w"] },
    { word: "Porco", transcription: ["p", "o", "ʁ", "k", "u"] },
    { word: "Nariz", transcription: ["n", "a", "ɾ", "i", "s"] },
    { word: "Amor", transcription: ["a", "m", "o", "ʁ"] },
    { word: "Roupa", transcription: ["ʁ", "o", "w", "p", "ɐ"] },
];

export const wordsNomeation: WordAndTranscription[] = [
    { word: "Palhaço", transcription: ["p", "a", "ʎ", "a", "s", "u"] },
    { word: "Bolsa", transcription: ["b", "o", "w", "s", "ɐ"] },
    { word: "Tesoura", transcription: ["t", "e", "z", "o", "w", "ɾ", "ɐ"] },
    { word: "Cadeira", transcription: ["k", "a", "d", "e", "j", "ɾ", "ɐ"] },
    { word: "Galinha", transcription: ["g", "a", "ʎ", "i", "ɲ", "ɐ"] },
    { word: "Vassoura", transcription: ["v", "a", "s", "o", "w", "ɾ", "ɐ"] },
    { word: "Cebola", transcription: ["s", "e", "b", "o", "l", "ɐ"] },
    { word: "Xícara", transcription: ["ʃ", "i", "k", "a", "ɾ", "ɐ"] },
    { word: "Mesa", transcription: ["m", "e", "z", "ɐ"] },
    { word: "Navio", transcription: ["n", "a", "v", "i", "w"] },
    { word: "Livro", transcription: ["l", "i", "v", "ɾ", "u"] },
    { word: "Sapo", transcription: ["s", "a", "p", "u"] },
    { word: "Tambor", transcription: ["t", "ɐ̃", "b", "o", "ʁ"] },
    { word: "Sapato", transcription: ["s", "a", "p", "a", "t", "u"] },
    { word: "Balde", transcription: ["b", "a", "w", "d", "ʒ", "i"] },
    { word: "Faca", transcription: ["f", "a", "k", "ɐ"] },
    { word: "Fogão", transcription: ["f", "o", "g", "ɐ̃", "w"] },
    { word: "Peixe", transcription: ["p", "e", "j", "ʃ", "i"] },
    { word: "Relógio", transcription: ["ʁ", "e", "l", "ɔ", "ʒ", "u"] },
    { word: "Cama", transcription: ["k", "ɐ", "m", "ɐ"] },
    { word: "Anel", transcription: ["a", "n", "ɛ", "w"] },
    { word: "Milho", transcription: ["m", "i", "ʎ", "u"] },
    { word: "Cachorro", transcription: ["k", "a", "ʃ", "o", "ʁ", "u"] },
    { word: "Blusa", transcription: ["b", "l", "u", "z", "ɐ"] },
    { word: "Garfo", transcription: ["g", "a", "ʁ", "f", "u"] },
    { word: "Trator", transcription: ["t", "ɾ", "a", "t", "o", "ʁ"] },
    { word: "Prato", transcription: ["p", "ɾ", "a", "t", "u"] },
    { word: "Pasta", transcription: ["p", "a", "s", "t", "ɐ"] },
    { word: "Dedo", transcription: ["d", "e", "d", "u"] },
    { word: "Braço", transcription: ["b", "ɾ", "a", "s", "u"] },
    { word: "Girafa", transcription: ["ʒ", "i", "ɾ", "a", "f", "ɐ"] },
    { word: "Zebra", transcription: ["z", "e", "b", "ɾ", "ɐ"] },
    { word: "Planta", transcription: ["p", "l", "ɐ̃", "t", "ɐ"] },
    { word: "Cruz", transcription: ["k", "ɾ", "u", "s"] },
];

export const consonants = ["ʃ", "ʒ", "ɲ", "ʎ", "X", "r", "ɻ"];

export const vowels = [
    "a",
    "ɐ",
    "ɛ",
    "e",
    "ẽ",
    "i",
    "j",
    "Ĩ",
    "ɔ",
    "o",
    "u",
    "w",
    "ũ",
];

export const phonems = [
    "p",
    "b",
    "m",
    "t",
    "d",
    "k",
    "g",
    "f",
    "v",
    "s",
    "z",
    "ʃ",
    "ʒ",
    "n",
    "ɲ",
    "l",
    "ʎ",
    "X",
    "r",
    "cLv",
    "cRv",
    "S",
    "R",
];
