import { WordAndTranscription } from "../../../interfaces/word";

export const wordsImitation: WordAndTranscription[] = [
    { word: "Peteca", transcription: ["pe", "ˈtɛ", "kɐ"] },
    { word: "Bandeja", transcription: ["bɐ̃", "ˈde", "ʒɐ"] },
    { word: "Tigela", transcription: ["tʃi", "ˈʒɛ", "lɐ"] },
    { word: "Doce", transcription: ["ˈdo", "sɪ"] },
    { word: "Cortina", transcription: ["koʁ", "ˈtʃi", "nɐ"] },
    { word: "Gato", transcription: ["ˈga", "tʊ"] },
    { word: "Foguete", transcription: ["fo", "ˈge", "tʃɪ"] },
    { word: "Vinho", transcription: ["ˈvĩ", "ɲʊ"] },
    { word: "Selo", transcription: ["ˈse", "lʊ"] },
    { word: "Zero", transcription: ["ˈzɛ", "ɾʊ"] },
    { word: "Chuva", transcription: ["ˈʃu", "vɐ"] },
    { word: "Jacaré", transcription: ["ʒa", "ka", "ˈɾɛ"] },
    { word: "Machado", transcription: ["ma", "ˈʃa", "dʊ"] },
    { word: "Nata", transcription: ["ˈna", "tɐ"] },
    { word: "Lama", transcription: ["ˈlɐ", "mɐ"] },
    { word: "Ônibus", transcription: ["ˈõ", "ni", "bʊs"] },
    { word: "Prego", transcription: ["ˈpɾɛ", "gʊ"] },
    { word: "Café", transcription: ["ka", "ˈfɛ"] },
    { word: "Alface", transcription: ["aw", "ˈfa", "sɪ"] },
    { word: "Raposa", transcription: ["ʁa", "ˈpo", "zɐ"] },
    { word: "Borracha", transcription: ["bo", "ˈʁa", "ʃɐ"] },
    { word: "Abelha", transcription: ["a", "ˈbe", "ʎɐ"] },
    { word: "Carro", transcription: ["ˈka", "ʁʊ"] },
    { word: "Branco", transcription: ["ˈbɾɐ̃", "kʊ"] },
    { word: "Travessa", transcription: ["tɾa", "ˈvɛ", "sɐ"] },
    { word: "Droga", transcription: ["ˈdɾɔ", "gɐ"] },
    { word: "Cravo", transcription: ["ˈkɾa", "vʊ"] },
    { word: "Grosso", transcription: ["ˈgɾo", "sʊ"] },
    { word: "Fraco", transcription: ["ˈfɾa", "kʊ"] },
    { word: "Plástico", transcription: ["ˈplas", "tʃi", "kʊ"] },
    { word: "Bloco", transcription: ["ˈblɔ", "kʊ"] },
    { word: "Clube", transcription: ["ˈklu", "bɪ"] },
    { word: "Globo", transcription: ["ˈglo", "bʊ"] },
    { word: "Flauta", transcription: ["ˈflaw", "tɐ"] },
    { word: "Pastel", transcription: ["pas", "ˈtɛw"] },
    { word: "Porco", transcription: ["ˈpoʁ", "kʊ"] },
    { word: "Nariz", transcription: ["na", "ˈɾis"] },
    { word: "Amor", transcription: ["a", "ˈmoʁ"] },
    { word: "Roupa", transcription: ["ˈhow", "pɐ"] },
];

export const wordsNomeation: WordAndTranscription[] = [
    { word: "Palhaço", transcription: ["pa", "ˈʎa", "sʊ"] },
    { word: "Bolsa", transcription: ["ˈbow", "sɐ"] },
    { word: "Tesoura", transcription: ["tʃi", "ˈzow", "ɾɐ"] },
    { word: "Cadeira", transcription: ["ka", "ˈdej", "ɾɐ"] },
    { word: "Galinha", transcription: ["ga", "ˈʎi", "ɲɐ"] },
    { word: "Vassoura", transcription: ["va", "ˈsow", "ɾɐ"] },
    { word: "Cebola", transcription: ["se", "ˈbolɐ"] },
    { word: "Xícara", transcription: ["ˈʃi", "ka", "ɾɐ"] },
    { word: "Mesa", transcription: ["ˈme", "zɐ"] },
    { word: "Navio", transcription: ["na", "ˈviw"] },
    { word: "Livro", transcription: ["ˈli", "vɾʊ"] },
    { word: "Sapo", transcription: ["ˈsa", "pʊ"] },
    { word: "Tambor", transcription: ["tɐ̃", "ˈboʁ"] },
    { word: "Sapato", transcription: ["sa", "ˈpa", "tʊ"] },
    { word: "Balde", transcription: ["ˈbaw", "dʒɪ"] },
    { word: "Faca", transcription: ["ˈfa", "kɐ"] },
    { word: "Fogão", transcription: ["fo", "ˈgɐ̃w"] },
    { word: "Peixe", transcription: ["ˈpej", "ʃɪ"] },
    { word: "Relógio", transcription: ["ʁe", "ˈlɔ", "ʒʊ"] },
    { word: "Cama", transcription: ["ˈkɐ", "mɐ"] },
    { word: "Anel", transcription: ["a", "ˈnɛw"] },
    { word: "Milho", transcription: ["ˈmi", "ʎʊ"] },
    { word: "Cachorro", transcription: ["ka", "ˈʃo", "ʁʊ"] },
    { word: "Blusa", transcription: ["ˈblu", "zɐ"] },
    { word: "Garfo", transcription: ["ˈgaʁ", "fʊ"] },
    { word: "Trator", transcription: ["tɾa", "ˈtoʁ"] },
    { word: "Prato", transcription: ["ˈpɾa", "tʊ"] },
    { word: "Pasta", transcription: ["ˈpas", "tɐ"] },
    { word: "Dedo", transcription: ["ˈde", "dʊ"] },
    { word: "Braço", transcription: ["ˈbɾa", "sʊ"] },
    { word: "Girafa", transcription: ["ʒi", "ˈɾa", "fɐ"] },
    { word: "Zebra", transcription: ["ˈze", "bɾɐ"] },
    { word: "Planta", transcription: ["ˈplɐ̃", "tɐ"] },
    { word: "Cruz", transcription: ["ˈkɾus"] },
];

export const consonants = [
    "p",
    "b",
    "t",
    "d",
    "k",
    "g",
    "ʔ",
    "f",
    "v",
    "θ",
    "ð",
    "s",
    "z",
    "ʃ",
    "ʒ",
    "h",
    "m",
    "n",
    "ŋ",
    "l",
    "r",
    "ɹ",
    "w",
    "j",
    "tʃ",
    "dʒ",
    "ts",
    "dz",
];

export const vowels = [
    "i",
    "ɪ",
    "e",
    "ɛ",
    "æ",
    "a",
    "ɑ",
    "ɔ",
    "o",
    "ʊ",
    "u",
    "ɨ",
    "ə",
    "ɚ",
    "ɝ",
    "ʌ",
    "ɒ",
];

export const diacritics = ["ˈ", "ˌ", ":", "ʰ", "ʷ", "ʲ", "ⁿ", "̃", "̥", "̬"];
