import { WordAndTranscription } from "../../../interfaces/word";

//TODO: atualizar todas as transcrições com a tabela de aurora, usar uma string em vez de array de strings
export const wordsImitation: WordAndTranscription[] = [
    { word: "Peteca", transcription: "pɛ.tɛ.kɐ" },
    { word: "Bandeja", transcription: "bã.de.ʒɐ" },
    { word: "Tigela", transcription: "ti.ʒɛ.lɐ" },
    { word: "Doce", transcription: "do.si" },
    { word: "Cortina", transcription: "kox.tĩ.na" },
    { word: "Gato", transcription: "ga.tu" },
    { word: "Foguete", transcription: "fu.ge.ti" },
    { word: "Vinho", transcription: "vĩ.ɲu" },
    { word: "Selo", transcription: "se.lu" },
    { word: "Zero", transcription: "zɛ.ru" },
    { word: "Chuva", transcription: "ʃu.vɐ" },
    { word: "Jacaré", transcription: "ʒa.ka.rɛ" },
    { word: "Machado", transcription: "ma.ʃa.du" },
    { word: "Nata", transcription: "na.tɐ" },
    { word: "Lama", transcription: "lã.mɐ" },
    { word: "Ônibus", transcription: "õ.ni.bus" },
    { word: "Prego", transcription: "prɛ.gu" },
    { word: "Café", transcription: "ka.fɛ" },
    { word: "Alface", transcription: "aw.fa.si" },
    { word: "Raposa", transcription: "ra.po.zɐ" },
    { word: "Borracha", transcription: "bu.xa.ʃɐ" },
    { word: "Abelha", transcription: "a.be.ʎɐ" },
    { word: "Carro", transcription: "ka.xu" },
    { word: "Branco", transcription: "brã.ku" },
    { word: "Travessa", transcription: "tra.vɛ.sɐ" },
    { word: "Dragão", transcription: "dra.gãw" },
    { word: "Cravo", transcription: "kra.vu" },
    { word: "Grosso", transcription: "gro.su" },
    { word: "Fraco", transcription: "fra.ku" },
    { word: "Plástico", transcription: "plas.ti.ku" },
    { word: "Bloco", transcription: "blɔ.ku" },
    { word: "Clube", transcription: "klu.bi" },
    { word: "Globo", transcription: "glo.bu" },
    { word: "Flauta", transcription: "flaw.ta" },
    { word: "Pastel", transcription: "pas.tɛw" },
    { word: "Porco", transcription: "pox.ku" },
    { word: "Nariz", transcription: "na.ris" },
    { word: "Amor", transcription: "a.mox" },
    { word: "Roupa", transcription: "row.pɐ" },
];

export const wordsNomeation: WordAndTranscription[] = [
    { word: "Palhaço", transcription: "pa.ʎa.su" },
    { word: "Bolsa", transcription: "bow.sɐ" },
    { word: "Tesoura", transcription: "ti.zow.ra" },
    { word: "Cadeira", transcription: "ka.dej.rɐ" },
    { word: "Galinha", transcription: "ga.lĩ.ɲɐ" },
    { word: "Vassoura", transcription: "va.sow.rɐ" },
    { word: "Cebola", transcription: "se.bo.lɐ" },
    { word: "Xícara", transcription: "ʃi.kɐ.rɐ" },
    { word: "Mesa", transcription: "me.zɐ" },
    { word: "Navio", transcription: "na.viw" },
    { word: "Livro", transcription: "li.vru" },
    { word: "Sapo", transcription: "sa.pu" },
    { word: "Tambor", transcription: "tã.box" },
    { word: "Sapato", transcription: "sa.pa.tu" },
    { word: "Balde", transcription: "baw.di" },
    { word: "Faca", transcription: "fa.kɐ" },
    { word: "Fogão", transcription: "fu.gãw" },
    { word: "Peixe", transcription: "pej.ʃi" },
    { word: "Relógio", transcription: "xɛ.lɔ.ʒiw" },
    { word: "Cama", transcription: "kã.mɐ" },
    { word: "Anel", transcription: "a.nɛw" },
    { word: "Milho", transcription: "mi.ʎu" },
    { word: "Cachorro", transcription: "ka.ʃo.xu" },
    { word: "Blusa", transcription: "blu.zɐ" },
    { word: "Garfo", transcription: "gax.fu" },
    { word: "Trator", transcription: "tra.tox" },
    { word: "Prato", transcription: "pra.tu" },
    { word: "Pasta", transcription: "pas.tɐ" },
    { word: "Dedo", transcription: "de.du" },
    { word: "Braço", transcription: "bra.su" },
    { word: "Girafa", transcription: "ʒi.ra.fɐ" },
    { word: "Zebra", transcription: "ze.brɐ" },
    { word: "Planta", transcription: "plã.tɐ" },
    { word: "Cruz", transcription: "krus" },
];

export const consonants = ["ʃ", "ʒ", "ɲ", "ʎ", "x", "r", "ɻ"];

export const vowels = [
    "a",
    "ɐ",
    "ɛ",
    "e",
    "ẽ",
    "i",
    "j",
    "Ĩ",
    "ɔ",
    "o",
    "u",
    "w",
    "ũ",
];

export const phonemes = [
    "p",
    "b",
    "m",
    "t",
    "d",
    "k",
    "g",
    "f",
    "v",
    "s",
    "z",
    "ʃ",
    "ʒ",
    "n",
    "ɲ",
    "l",
    "ʎ",
    "x",
    "r",
    "cLv",
    "cRv",
    "[S]",
    "[R]",
];
